export const blogs = [{
        image: "/assets/image/blog1.jpg",
        title: "how to own your audience by creating an email list",
        text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsa esse adipisci ea. Dolore eveniet cum enim excepturi impedit tenetur beatae.",
        person: "rio",
        date: "12 april 2021",
        work: "wordpress, business, economy",
    },
    {
        image: "/assets/image/blog1.jpg",
        title: "how to own your audience by creating an email list",
        text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsa esse adipisci ea. Dolore eveniet cum enim excepturi impedit tenetur beatae.",
        person: "rio",
        date: "12 april 2021",
        work: "wordpress, business, economy",
    },
    {
        image: "/assets/image/blog1.jpg",
        title: "how to own your audience by creating an email list",
        text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsa esse adipisci ea. Dolore eveniet cum enim excepturi impedit tenetur beatae.",
        person: "rio",
        date: "12 april 2021",
        work: "wordpress, business, economy",
    },
    {
        image: "/assets/image/blog1.jpg",
        title: "how to own your audience by creating an email list",
        text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsa esse adipisci ea. Dolore eveniet cum enim excepturi impedit tenetur beatae.",
        person: "rio",
        date: "12 april 2021",
        work: "wordpress, business, economy",
    },
    {
        image: "/assets/image/blog1.jpg",
        title: "how to own your audience by creating an email list",
        text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsa esse adipisci ea. Dolore eveniet cum enim excepturi impedit tenetur beatae.",
        person: "rio",
        date: "12 april 2021",
        work: "wordpress, business, economy",
    },
    {
        image: "/assets/image/blog1.jpg",
        title: "how to own your audience by creating an email list",
        text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsa esse adipisci ea. Dolore eveniet cum enim excepturi impedit tenetur beatae.",
        person: "rio",
        date: "12 april 2021",
        work: "wordpress, business, economy",
    },
];
export const portfolios = {
    logo: ["src", "src", "src"],
    video: ["src", "src", "src"],
    graphicDesign: ["src", "src", "src"],
};